<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simucomtooladapter" nsURI="http://palladiosimulator.org/ExperimentAutomation/ToolAdapter/SimuCom/1.0"
    nsPrefix="simucomtooladapter">
  <eClassifiers xsi:type="ecore:EClass" name="SimuComConfiguration" eSuperTypes="../../org.palladiosimulator.experimentautomation/model/experimentautomation.ecore#//abstractsimulation/AbstractSimulationConfiguration"/>
</ecore:EPackage>
