/**
 */
package org.palladiosimulator.experimentautomation.abstractsimulation.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.palladiosimulator.experimentautomation.abstractsimulation.util.AbstractsimulationAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The
 * adapters generated by this factory convert EMF adapter notifications into calls to
 * {@link #fireNotifyChanged fireNotifyChanged}. The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 *
 * @generated
 */
public class AbstractsimulationItemProviderAdapterFactory extends AbstractsimulationAdapterFactory implements
        ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType
     * isFactoryForType}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public AbstractsimulationItemProviderAdapterFactory() {
        this.supportedTypes.add(IEditingDomainItemProvider.class);
        this.supportedTypes.add(IStructuredItemContentProvider.class);
        this.supportedTypes.add(ITreeItemContentProvider.class);
        this.supportedTypes.add(IItemLabelProvider.class);
        this.supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.RandomNumberGeneratorSeed}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected RandomNumberGeneratorSeedItemProvider randomNumberGeneratorSeedItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.RandomNumberGeneratorSeed}
     * . <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRandomNumberGeneratorSeedAdapter() {
        if (this.randomNumberGeneratorSeedItemProvider == null) {
            this.randomNumberGeneratorSeedItemProvider = new RandomNumberGeneratorSeedItemProvider(this);
        }

        return this.randomNumberGeneratorSeedItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.SensorFramework}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected SensorFrameworkItemProvider sensorFrameworkItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.SensorFramework}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSensorFrameworkAdapter() {
        if (this.sensorFrameworkItemProvider == null) {
            this.sensorFrameworkItemProvider = new SensorFrameworkItemProvider(this);
        }

        return this.sensorFrameworkItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.MemoryDatasource}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected MemoryDatasourceItemProvider memoryDatasourceItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.MemoryDatasource}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createMemoryDatasourceAdapter() {
        if (this.memoryDatasourceItemProvider == null) {
            this.memoryDatasourceItemProvider = new MemoryDatasourceItemProvider(this);
        }

        return this.memoryDatasourceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.FileDatasource}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected FileDatasourceItemProvider fileDatasourceItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.FileDatasource}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createFileDatasourceAdapter() {
        if (this.fileDatasourceItemProvider == null) {
            this.fileDatasourceItemProvider = new FileDatasourceItemProvider(this);
        }

        return this.fileDatasourceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.MeasurementCountStopCondition}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected MeasurementCountStopConditionItemProvider measurementCountStopConditionItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.MeasurementCountStopCondition}
     * . <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createMeasurementCountStopConditionAdapter() {
        if (this.measurementCountStopConditionItemProvider == null) {
            this.measurementCountStopConditionItemProvider = new MeasurementCountStopConditionItemProvider(this);
        }

        return this.measurementCountStopConditionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.SimTimeStopCondition}
     * instances. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected SimTimeStopConditionItemProvider simTimeStopConditionItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.SimTimeStopCondition}.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createSimTimeStopConditionAdapter() {
        if (this.simTimeStopConditionItemProvider == null) {
            this.simTimeStopConditionItemProvider = new SimTimeStopConditionItemProvider(this);
        }

        return this.simTimeStopConditionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.EDP2} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected EDP2ItemProvider edp2ItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.palladiosimulator.experimentautomation.abstractsimulation.EDP2}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createEDP2Adapter() {
        if (this.edp2ItemProvider == null) {
            this.edp2ItemProvider = new EDP2ItemProvider(this);
        }

        return this.edp2ItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void setParentAdapterFactory(final ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public boolean isFactoryForType(final Object type) {
        return this.supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter adapt(final Notifier notifier, final Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Object adapt(final Object object, final Object type) {
        if (this.isFactoryForType(type)) {
            final Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void addListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void removeListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void fireNotifyChanged(final Notification notification) {
        this.changeNotifier.fireNotifyChanged(notification);

        if (this.parentAdapterFactory != null) {
            this.parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public void dispose() {
        if (this.randomNumberGeneratorSeedItemProvider != null) {
            this.randomNumberGeneratorSeedItemProvider.dispose();
        }
        if (this.sensorFrameworkItemProvider != null) {
            this.sensorFrameworkItemProvider.dispose();
        }
        if (this.memoryDatasourceItemProvider != null) {
            this.memoryDatasourceItemProvider.dispose();
        }
        if (this.fileDatasourceItemProvider != null) {
            this.fileDatasourceItemProvider.dispose();
        }
        if (this.measurementCountStopConditionItemProvider != null) {
            this.measurementCountStopConditionItemProvider.dispose();
        }
        if (this.simTimeStopConditionItemProvider != null) {
            this.simTimeStopConditionItemProvider.dispose();
        }
        if (this.edp2ItemProvider != null) {
            this.edp2ItemProvider.dispose();
        }
    }

}
